name = "ofa-cal"
main = "src/index.ts"
compatibility_date = "2023-03-25"
keep_vars = true
workers_dev = false

kv_namespaces = [
  { binding = "GUILDS", id = "a042c5e627cf42bfa4be510355314de8", preview_id = "70993ba0bdec4bacbf8ea241c848c742" }
]

[env.local]

[triggers]
crons = [ "1 * * * *" ]
