name = "ofa-cal"
main = "src/index.ts"
compatibility_date = "2023-03-25"
keep_vars = true
workers_dev = false

kv_namespaces = [
  { binding = "GUILDS", id = "18c1bf66a41b423e90458c51024c1f1c", preview_id = "18c1bf66a41b423e90458c51024c1f1c" }
]

[env.local]

[triggers]
crons = [ "1 * * * *" ]
